"""
Generate the evaluation test-set.

Produces ``backend/tests/test_data``:

  real/   known real photographs (public-domain / sample images)
  ai/     known AI-generated images (FLUX.1-schnell, generated on the fly)
  variants/  recompressed / resized copies of the above (JPEG/PNG)
  screenshots/  synthetic UI screenshots (edge cases, reported separately)

Run with the 64-bit ML runtime::

    pwsh> & "$env:LOCALAPPDATA/unmask-ai/runtime/py312/python.exe" backend/tests/generate_test_data.py
"""

from __future__ import annotations

import io
import sys
from pathlib import Path

import requests
from PIL import Image, ImageDraw, ImageFilter

TEST_DIR = Path(__file__).resolve().parent / "test_data"
REAL_DIR = TEST_DIR / "real"
AI_DIR = TEST_DIR / "ai"
VAR_DIR = TEST_DIR / "variants"
SHOT_DIR = TEST_DIR / "screenshots"

MISHIG = "https://huggingface.co/datasets/mishig/sample_images/resolve/main/{}"
REAL_SAMPLE_FILES = [
    "tiger.jpg",
    "cat-1.jpg",
    "dog-cat.jpg",
    "palace.jpg",
    "teapot.jpg",
    "savanna.jpg",
    "airport.jpg",
    "construction-site.jpg",
]

FLUX_PROMPTS = [
    "a fluffy white cat sitting on a wooden table, studio photo",
    "a majestic mountain landscape at sunset with a lake reflection, photograph",
    "a smiling woman portrait with soft studio lighting, photorealistic",
    "a futuristic city skyline at night with neon lights, photorealistic",
    "a delicious gourmet burger on a wooden board, food photography",
    "an elderly man with a beard looking at the camera, photorealistic portrait",
    "a golden retriever puppy playing in a park, photorealistic",
    "a cozy cabin in a snowy forest at dusk, photorealistic landscape",
    "fresh strawberries on a white ceramic bowl, macro photography",
    "a vintage car parked on a coastal road, golden hour, photorealistic",
]


def download_real_photos() -> None:
    REAL_DIR.mkdir(parents=True, exist_ok=True)
    for name in REAL_SAMPLE_FILES:
        target = REAL_DIR / name
        if target.exists():
            continue
        r = requests.get(MISHIG.format(name), timeout=60)
        r.raise_for_status()
        target.write_bytes(r.content)
        print("downloaded", name, len(r.content), "bytes")


def copy_skimage_photos() -> None:
    import skimage.data

    REAL_DIR.mkdir(parents=True, exist_ok=True)
    for name in ("astronaut", "camera", "chelsea", "coffee", "rocket"):
        img = getattr(skimage.data, name)()
        pil = Image.fromarray(img).convert("RGB")
        target = REAL_DIR / f"skimage-{name}.png"
        if not target.exists():
            pil.save(target, format="PNG")
            print("saved", target.name)


COMMONS_CATEGORIES = [
    "Category:Images generated by DALL-E",
    "Category:Images generated by Stable Diffusion",
]


def generate_ai_images() -> None:
    AI_DIR.mkdir(parents=True, exist_ok=True)
    try:
        from gradio_client import Client
    except ImportError:
        print("gradio_client not installed — skipping FLUX generation.")
    else:
        client = Client("black-forest-labs/FLUX.1-schnell", verbose=False)
        for i, prompt in enumerate(FLUX_PROMPTS):
            target = AI_DIR / f"flux-{i:02d}.png"
            if target.exists():
                continue
            print(f"generating [{i + 1}/{len(FLUX_PROMPTS)}]: {prompt!r} …")
            try:
                res = client.predict(
                    prompt=prompt,
                    seed=1000 + i,
                    randomize_seed=False,
                    width=512,
                    height=512,
                    num_inference_steps=2,
                    api_name="/infer",
                )
            except Exception as e:
                print(f"  FLUX failed ({e}); switching to Commons fallback.")
                break
            path = res[0] if isinstance(res, tuple) else res
            img = Image.open(path).convert("RGB")
            img.save(target, format="PNG")
            print("saved", target.name)

    # Fall back on Wikimedia Commons for any remaining slots.
    existing = sorted(AI_DIR.glob("*"))
    if len(existing) >= len(FLUX_PROMPTS):
        return

    headers = {"User-Agent": "UnmaskAI-Eval/1.0 (test-suite)"}
    urls: list[tuple[str, str]] = []  # (file title, thumb url)
    for cat in COMMONS_CATEGORIES:
        params = {
            "action": "query",
            "generator": "categorymembers",
            "gcmtitle": cat,
            "gcmtype": "file",
            "prop": "imageinfo",
            "iiprop": "url",
            "iiurlwidth": "512",
            "format": "json",
            "gcmlimit": "30",
        }
        r = requests.get("https://commons.wikimedia.org/w/api.php", params=params, headers=headers, timeout=30)
        r.raise_for_status()
        for page in r.json().get("query", {}).get("pages", {}).values():
            info = page.get("imageinfo", [{}])[0]
            thumb = info.get("thumburl")
            if thumb:
                urls.append((page["title"], thumb))

    n = 0
    for title, url in urls:
        if n >= len(FLUX_PROMPTS) - len(existing):
            break
        if not title.lower().endswith((".jpg", ".jpeg", ".png")):
            continue
        target = AI_DIR / f"commons-{n:02d}.jpg"
        if target.exists():
            n += 1
            continue
        img = None
        for attempt in range(3):
            try:
                data = requests.get(url, headers=headers, timeout=60).content
                if not data[:2] == b"\xff\xd8" and b"PNG" not in data[:16]:
                    raise ValueError("not an image payload (rate-limited page?)")
                img = Image.open(io.BytesIO(data)).convert("RGB")
                break
            except Exception as e:
                print(f"  attempt {attempt + 1} failed for {title}: {e}")
        if img is None:
            continue
        img.save(target, format="JPEG", quality=90)
        print(f"saved {target.name}  <-  {title}")
        n += 1


def make_variants() -> None:
    """Recompress / resize base images to simulate real-world uploads."""
    VAR_DIR.mkdir(parents=True, exist_ok=True)

    def variant_of(src: Path, out_name: str, transform) -> None:
        out = VAR_DIR / out_name
        if out.exists():
            return
        img = Image.open(src).convert("RGB")
        transform(img).save(out)
        print("saved", out_name)

    for kind, folder in (("real", REAL_DIR), ("ai", AI_DIR)):
        for src in sorted(folder.glob("*")):
            stem = src.stem
            ext = src.suffix.lower()
            # JPEG recompression at two qualities
            variant_of(src, f"{stem}-jpeg-q85.jpg", lambda im: _encode_jpeg(im, 85))
            variant_of(src, f"{stem}-jpeg-q60.jpg", lambda im: _encode_jpeg(im, 60))
            # PNG re-encode
            if ext != ".png":
                variant_of(src, f"{stem}-png.png", lambda im: im)
            # Downscale / upscale
            variant_of(src, f"{stem}-down-50pct.jpg", lambda im: _encode_jpeg(im.resize((im.width // 2, im.height // 2)), 85))
            variant_of(src, f"{stem}-up-200pct.jpg", lambda im: _encode_jpeg(im.resize((im.width * 2, im.height * 2), Image.LANCZOS), 85))


def _encode_jpeg(img: Image.Image, quality: int) -> Image.Image:
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=quality)
    buf.seek(0)
    return Image.open(buf).convert("RGB")


def make_screenshots() -> None:
    """Synthetic UI screenshots (edge cases — not photographs, not AI art)."""
    SHOT_DIR.mkdir(parents=True, exist_ok=True)
    palette = [(20, 24, 28), (30, 34, 40), (10, 12, 16), (40, 120, 80), (220, 60, 60), (240, 240, 240)]

    def draw_screen(name: str, mode: str) -> None:
        out = SHOT_DIR / name
        if out.exists():
            return
        img = Image.new("RGB", (480, 320), palette[2])
        d = ImageDraw.Draw(img)
        d.rectangle([0, 0, 480, 28], fill=palette[1])
        d.text((10, 6), "MyApp  -  Dashboard", fill=palette[5])
        if mode == "dashboard":
            d.rectangle([20, 50, 220, 250], outline=palette[3], width=2)
            d.rectangle([240, 50, 460, 250], outline=palette[3], width=2)
            for x in range(24, 220, 20):
                d.rectangle([x, 240 - (x % 7) * 8, x + 12, 244], fill=palette[0])
            d.rectangle([60, 150, 160, 155], fill=palette[0])
            d.rectangle([280, 120, 420, 125], fill=palette[0])
        elif mode == "text":
            for i, line in enumerate(
                ["Settings", "Account", "Notifications", "Privacy", "Help", "About"],
            ):
                d.text((30, 60 + i * 32), line, fill=palette[5])
                d.rectangle([30, 72 + i * 32, 200, 74 + i * 32], fill=palette[0])
        elif mode == "photo_editor":
            d.rectangle([20, 40, 300, 280], fill=palette[1])
            d.rectangle([320, 40, 460, 280], outline=palette[4], width=2)
            d.text((330, 120), "Brightness", fill=palette[5])
            d.rectangle([330, 150, 430, 152], fill=palette[3])
        img.save(out, format="PNG")
        print("saved", name)

    draw_screen("dashboard.png", "dashboard")
    draw_screen("settings-text.png", "text")
    draw_screen("photo-editor.png", "photo_editor")


def main() -> None:
    print("==> Real photographs")
    download_real_photos()
    copy_skimage_photos()

    print("==> AI-generated images (FLUX)")
    generate_ai_images()

    print("==> Variants (recompress / resize)")
    make_variants()

    print("==> Screenshots (edge cases)")
    make_screenshots()

    for folder in (REAL_DIR, AI_DIR, VAR_DIR, SHOT_DIR):
        n = len(list(folder.glob("*")))
        print(f"{folder.name}: {n} files")


if __name__ == "__main__":
    sys.exit(main())
