import { useState } from 'react';
import { motion } from 'framer-motion';
import { ScanLine, Home, ArrowLeft, WifiOff } from 'lucide-react';
import { navigate } from '../lib/router';

interface NotFoundPageProps {
  variant?: 'notfound' | 'network';
}

export default function NotFoundPage({ variant = 'notfound' }: NotFoundPageProps) {
  const network = variant === 'network';
  const [detail] = useState<string | null>(() => {
    if (!network) return null;
    try {
      return sessionStorage.getItem('unmask:error-message');
    } catch {
      return null;
    }
  });

  return (
    <section className="relative z-10 flex min-h-[72vh] items-center justify-center px-4 py-20">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="w-full max-w-md text-center"
      >
        <motion.div
          animate={{ rotate: [0, 6, -6, 0], scale: [1, 1.04, 1] }}
          transition={{ duration: 2.4, repeat: Infinity, ease: 'easeInOut' }}
          className="mx-auto grid h-20 w-20 place-items-center rounded-3xl border border-danger/30 bg-danger/10 shadow-[0_0_40px_rgba(255,59,59,0.25)]"
        >
          {network ? (
            <WifiOff className="h-10 w-10 text-danger" strokeWidth={1.8} />
          ) : (
            <ScanLine className="h-10 w-10 text-danger" strokeWidth={1.8} />
          )}
        </motion.div>

        <p className="mt-8 text-sm font-semibold uppercase tracking-[0.3em] text-danger/80">Error 404</p>
        <h1 className="mt-2 text-5xl font-bold tracking-tight text-white">
          {network ? (
            <>
              Network <span className="neon-text">error</span>
            </>
          ) : (
            <>
              Page not <span className="neon-text">found</span>
            </>
          )}
        </h1>
        <p className="mx-auto mt-4 max-w-sm text-sm leading-relaxed text-white/50">
          {network
            ? detail || 'We could not reach the detection service. Check your internet connection and try again.'
            : 'The pixel you are looking for does not exist. It may have been moved, deleted, or generated by an AI.'}
        </p>

        <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row">
          <button
            onClick={() => navigate('home')}
            className="liquid-btn flex items-center justify-center gap-2 rounded-xl bg-neon px-6 py-3 text-sm font-bold text-black"
          >
            <Home className="h-4 w-4" /> Go Home
          </button>
          <button
            onClick={() => window.history.length > 1 ? window.history.back() : navigate('home')}
            className="flex items-center justify-center gap-2 rounded-xl border border-white/10 px-6 py-3 text-sm font-semibold text-white/60 transition-colors hover:bg-white/5 hover:text-white"
          >
            <ArrowLeft className="h-4 w-4" /> Go Back
          </button>
        </div>
      </motion.div>
    </section>
  );
}
