import { useEffect, useState } from 'react';
import { ArrowRight, ShieldCheck } from 'lucide-react';
import { getShare, type ScanRecord } from '../api';
import { navigate } from '../lib/router';
import { CardSkeleton } from './Skeleton';

function verdictColor(verdict: string) {
  if (verdict === 'ai') return 'text-danger border-danger/30 bg-danger/10';
  if (verdict === 'real') return 'text-neon border-neon/30 bg-neon/10';
  return 'text-amber-300 border-amber-400/30 bg-amber-400/10';
}

export default function ShareView({ shareId }: { shareId: string }) {
  const [scan, setScan] = useState<ScanRecord | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      try {
        const res = await getShare(shareId);
        setScan(res.result);
      } catch (e) {
        setError(e instanceof Error ? e.message : 'Share not found');
      }
    })();
  }, [shareId]);

  if (error) {
    return (
      <section className="mx-auto max-w-2xl px-4 py-20 text-center">
        <div className="glass rounded-3xl p-10">
          <p className="text-lg font-bold text-white">Share link unavailable</p>
          <p className="mt-2 text-sm text-white/40">{error}</p>
          <button onClick={() => navigate('home')} className="btn-primary mt-6">Run your own scan</button>
        </div>
      </section>
    );
  }

  if (!scan) {
    return (
      <section className="mx-auto max-w-2xl px-4 py-10">
        <CardSkeleton />
      </section>
    );
  }

  const pct = scan.classification === 'REAL' ? scan.real_percent : scan.ai_percent;

  return (
    <section className="mx-auto max-w-2xl px-4 py-12">
      <div className="glass rounded-3xl p-6">
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="text-xs uppercase tracking-widest text-white/40">Shared analysis result</p>
            <h1 className="mt-1 text-2xl font-bold text-white">{scan.filename}</h1>
          </div>
          <span className={`rounded-full border px-3 py-1 text-xs font-bold uppercase ${verdictColor(scan.verdict)}`}>
            {scan.verdict}
          </span>
        </div>

        <div className="mt-6">
          <div className="flex items-end justify-between">
            <p className="text-4xl font-extrabold text-white">{pct.toFixed(1)}%</p>
            <p className="text-xs text-white/40">confidence {scan.confidence.toFixed(1)}%</p>
          </div>
          <div className="mt-2 h-3 overflow-hidden rounded-full bg-white/10">
            <div
              className={`h-full rounded-full ${scan.verdict === 'ai' ? 'bg-danger' : scan.verdict === 'real' ? 'bg-neon' : 'bg-amber-400'}`}
              style={{ width: `${pct}%` }}
            />
          </div>
          <p className="mt-2 text-sm text-white/50">
            Estimated likelihood this image was {scan.verdict === 'ai' ? 'generated by AI' : scan.verdict === 'real' ? 'captured by a camera' : 'inconclusive'}.
          </p>
        </div>

        {scan.heatmap && (
          <img
            src={`data:image/png;base64,${scan.heatmap}`}
            alt="AI attention heatmap"
            className="mt-6 aspect-video w-full rounded-2xl border border-white/10 object-cover"
          />
        )}

        {scan.indicators && scan.indicators.length > 0 && (
          <div className="mt-6 space-y-2">
            {scan.indicators.map((ind) => (
              <div key={ind.label} className="flex items-center gap-3 rounded-xl bg-white/[0.03] px-4 py-2.5">
                <span className="text-xs font-medium text-white/70">{ind.label}</span>
                <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/10">
                  <div className="h-full rounded-full bg-neon" style={{ width: `${ind.aiLikelihood * 100}%` }} />
                </div>
                <span className="text-xs font-bold text-white/70">{(ind.aiLikelihood * 100).toFixed(0)}</span>
              </div>
            ))}
          </div>
        )}

        <div className="mt-6 flex items-center gap-2 rounded-xl bg-white/[0.03] px-4 py-3 text-xs text-white/45">
          <ShieldCheck className="h-4 w-4 text-neon" />
          Original image was never stored. {scan.model ? `Model: ${scan.model}` : ''}
        </div>

        <button onClick={() => navigate('home')} className="btn-primary mt-6 w-full">
          Scan your own image <ArrowRight className="h-4 w-4" />
        </button>
      </div>
    </section>
  );
}
